var biovizWorkerNamespace = {};
(function(ns) {
var z,aa=[];function da(e){return function(){return aa[e].apply(this,arguments)}}function ea(){if(this.constructor===ea)throw Error("Can't instanciate abstract class BiovizMap");}z=ea.prototype;z.set=function(){throw Error("Trying to call an abstract method");};z.get=function(){throw Error("Trying to call an abstract method");};z.remove=function(){throw Error("Trying to call an abstract method");};z.Dc=function(){throw Error("Trying to call an abstract method");};
z.keys=function(){throw Error("Trying to call an abstract method");};z.values=function(){throw Error("Trying to call an abstract method");};z.clear=function(){throw Error("Trying to call an abstract method");};z.pd=da(2);function fa(){ea.call(this);this.ja=Object.create(null);this.Ef=Object.create(null);this.Ve={}.hasOwnProperty}fa.prototype=Object.create(ea.prototype);z=fa.prototype;z.constructor=fa;z.set=function(e,f){var g=ha(e);this.Dc(g);this.ja[g]=f;this.Ef[g]=e};
z.get=function(e){e=ha(e);return this.Dc(e)?this.ja[e]:null};z.remove=function(e){e=ha(e);if(this.Dc(e)){var f=this.ja[e];delete this.ja[e];delete this.Ef[e];return f}return null};z.Dc=function(e){e=ha(e);return this.Ve.call(this.ja,e)};z.keys=function(){var e=[],f;for(f in this.ja)e.push(f);return e};z.values=function(){var e=[],f;for(f in this.ja)e.push(this.ja[f]);return e};z.clear=function(){this.ja=Object.create(null);this.Ef=Object.create(null)};z.pd=da(1);
function ha(e){if(e instanceof Array){e=[];for(var f=e.length,g=0;g<f;g++)e.push(e[g].vb());return e.join("")}return e instanceof Object?e.vb():e}function ja(){ea.call(this);this.ja=[]}function ka(e,f){this.key=e;this.value=f}ja.prototype=Object.create(ea.prototype);z=ja.prototype;z.constructor=ja;
z.set=function(e,f){if(void 0===e)throw"ERROR: key cannot be undefined";var g;a:if(void 0!==e.kf)g=this.ja[e.kf];else{for(g in this.ja)if(this.ja[g].key===e){g=this.ja[g];break a}g=void 0}void 0===g?"object"===typeof e&&(e.kf=this.ja.push(new ka(e,f))-1):g.value=f};z.get=function(e){if(void 0!==e.kf)return this.ja[e.kf].value;for(var f in this.ja)if(this.ja[f].key===e)return this.ja[f].value};z.keys=function(){var e=[],f;for(f in this.ja)e.push(this.ja[f].key);return e};
z.Dc=function(e){return-1!==this.keys().indexOf(e)};z.values=function(){var e=[],f;for(f in this.ja)e.push(this.ja[f].value);return e};z.remove=function(e){var f=-1,g;for(g in this.ja)if(this.ja[g].key===e){f=g;break}return 0<=f?this.ja.splice(f,1)[0].value:null};z.clear=function(){this.ja=[]};z.pd=da(0);

function Ea(){this.pos=new THREE.Vector3;this.aa=this.wa=this.Wb=this.v=this.u=this.cc=this.da=this.symbol=this.ta=this.fa=this.ld=this.name=this.id=this.type=null}z=Ea.prototype;z.sa=function(){return this.id};z.mb=function(){return this.wa};function Ma(e,f){e.v!==f&&(e.v=f,null!==e.wa&&e.wa.bd(f))}z.Ka=function(){return this.pos};z.mc=function(){if(null===this.aa){var e=parseFloat(Ua.Fc(this.symbol)[7]),f=new THREE.Vector3(-e,-e,-e),e=new THREE.Vector3(e,e,e);this.aa=new Va(f,e)}return this.aa};
z.radius=function(){return parseFloat(Ua.Fc(this.symbol)[7])};z.lb=function(){return this.Wb};function $a(e,f){if(e.Wb!==f&&(e.Wb=f,null!=e.wa)){var g=e.wa,h=e.Wb;if(g.Wb!=h){g.Wb=h;for(var k=g.u.length,l=0;l<k;l++)$a(g.u[l],h)}}}z.Vc=function(){return this.cc};z.Je=function(e){this.cc!=e&&(this.cc=e,null!==this.wa&&this.wa.Je(e))};z.ue=function(){return this.u};z.Zd=function(e){this.u!==e&&(this.u=e,null!==this.wa&&this.wa.Zd(e))};
z.jk=function(){return this.wa.ea.da._id+":"+this.wa.ea.type+":"+this.wa.ea.id+":"+this.wa.cc+":"+this.wa._id+":"+this.name+":"+this.id};z.toString=function(){return this.symbol+":"+this.id};z.qd=function(){return this.wa.qd()+":"+this.toString()};z.vb=function(){return this.symbol+":"+this.id+":"+this.u};
z.distanceTo=function(e){return e instanceof Ea?Math.sqrt((this.pos.x-e.pos.x)*(this.pos.x-e.pos.x)+(this.pos.y-e.pos.y)*(this.pos.y-e.pos.y)+(this.pos.z-e.pos.z)*(this.pos.z-e.pos.z)):Math.sqrt((this.pos.x-e.x)*(this.pos.x-e.x)+(this.pos.y-e.y)*(this.pos.y-e.y)+(this.pos.z-e.z)*(this.pos.z-e.z))};z.sub=function(e){return e instanceof Ea?new THREE.Vector3(this.pos.x-e.pos.x,this.pos.y-e.pos.y,this.pos.z-e.pos.z):new THREE.Vector3(this.pos.x-e.x,this.pos.y-e.y,this.pos.z-e.z)};
z.add=function(e){return e instanceof Ea?new THREE.Vector3(this.pos.x+e.pos.x,this.pos.y+e.pos.y,this.pos.z+e.pos.z):new THREE.Vector3(this.pos.x+e.x,this.pos.y+e.y,this.pos.z+e.z)};z.clone=function(){return new THREE.Vector3(this.pos.x,this.pos.y,this.pos.z)};function ab(){this.fa=null;this.u=new ib;this.aa=[];this.ta=this.v=this.da=null}z=ab.prototype;z.Ec=function(){return this.fa};z.Ke=function(e){this.fa=e;e=this.aa.length;for(var f=0;f<e;f++)f.Ke(this.fa)};
z.add=function(e){if(e instanceof Ea)return e=this.u.Ff(e),ub(this),e;e instanceof vb?(null!==e.bc&&e.bc!==this&&console.warn("ERROR : ",e,"already belongs to",e.bc),null===e.bc&&(this.aa.push(e),e.Ke(this.fa),e.bc=this,ub(this))):console.warn("ERROR : a is not an atom or a molecule")};
z.remove=function(e){e instanceof Ea?(e=this.u.findNode(atom),-1<e&&(delete this.u[e],ub(this))):e instanceof vb&&(null===molecule&&console.warn("molecule null in remove, Model"),molecule.bc===this&&(this.aa.splice(this.aa.Ea(molecule),1),molecule.Ke(null),molecule.bc=null,ub(this)))};z.xa=function(){return this.u.values()};
z.ec=function(){if(!this.ta){console.log("Computing atoms bonds");this.u.Ej();console.log("Building atoms Octree");this.v=this.mc();for(var e=new wb(this.v.we(),this.v.ve(),32),f=this.xa(),g=f.length,h=0;h<g;h++)e.add(new xb(f[h]));e.optimize();console.log("Building bonds");g=f.length;for(h=0;h<g;h++)for(var k=f[h],l=k.symbol,l=l.charAt(0).toUpperCase()+l.slice(1).toLowerCase(),n=parseFloat(Ua.Fc(l)[6]),r=e.ah(k.pos,5),q=r.length,t=0;t<q;t++){var x=r[t].getPoint();if(x!==k){var l=x.symbol,l=l.charAt(0).toUpperCase()+
l.slice(1).toLowerCase(),l=parseFloat(Ua.Fc(l)[6]),w=k.distanceTo(x);if(w>=n+l-.4&&w<=n+l+.4){var l=k,w=this.u.findNode(l),C=this.u.findNode(x);void 0!==w&&void 0!==C||console.warn("Couldn't find atoms ",l," and/or ",x," in model ",this);w.Ei(C)||this.u.Kg(w,C).setAttribute("BondType","SIMPLE")}}}this.ta=!0}return this.u};function ub(e){e.da=null;e.v=null;e.ta=!1}
z.Ka=function(){if(null===this.da){this.da=new THREE.Vector3;for(var e=this.xa(),f=0,g=0,h=0,k=e.length,l=0;l<k;l++)var n=e[l].pos,f=f+parseInt(n.x),g=g+parseInt(n.y),h=h+parseInt(n.z);this.da.set(f/k,g/k,h/k)}return this.da};
z.mc=function(){if(null===this.v){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.xa(),h=g.length,k=0;k<h;k++){var l=g[k].pos;e.x=Math.min(e.x,l.x);e.y=Math.min(e.y,l.y);e.z=Math.min(e.z,l.z);f.x=Math.max(f.x,l.x);f.y=Math.max(f.y,l.y);f.z=Math.max(f.z,l.z)}this.v=new Va(e,f)}return this.v};function vb(e){this.id=e;this.bc=this.da=this.type=null;this.ia=[];this.v=this.aa=this.u=null;this.Ig=!1}z=vb.prototype;z.sa=function(){return this.id};
z.ec=function(){return this.bc.ec()};z.bd=function(e){if(this.id!==e){this.id=e;for(var f=0;f<this.ia.length;f++)this.ia[f].Zd(e)}};z.Ec=function(){return this.da};z.Ke=function(e){this.da=e};z.add=function(e){null==e&&console.warn("residue is null in Molecule");null!==e.ea&&e.ea!==this&&console.warn(e," already belongs to ",e.ea);null===e.ea&&(this.ia.push(e),Gb(e,this),Nb(this))};
z.remove=function(e){null===e&&console.warn("residue is null in Molecule");e.ea===this&&(this.ia.remove(e),Gb(e,null),Nb(this))};z.mb=function(e){for(var f=0;f<this.ia.length;f++){var g=this.ia[f];if(g.sa()==e)return g}return null};z.xa=function(){for(var e=[],f=this.ia.length,g=0;g<f;g++)e=e.concat(this.ia[g].xa());return e};z.size=function(){return this.ia.length};z.isEmpty=function(){return 0===this.size};function Nb(e){e.u=null;e.aa=null;null!==e.bc&&ub(e.bc)}
z.Ka=function(){if(null===this.u){this.u=new THREE.Vector3;for(var e=this.xa(),f=e.length,g=0;g<f;g++){var h=e[g].pos;this.u.x+=h.x;this.u.y+=h.y;this.u.z+=h.z}this.u.x/=f;this.u.y/=f;this.u.z/=f}return this.u};
z.mc=function(){if(null===this.aa){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.xa(),h=g.length,k=0;k<h;k++){var l=g[k].pos;e.x=Math.min(e.x,l.x);e.y=Math.min(e.y,l.y);e.z=Math.min(e.z,l.z);f.x=Math.max(f.x,l.x);f.y=Math.max(f.y,l.y);f.z=Math.max(f.z,l.z)}this.aa=new Va(e,f)}return this.aa};z.toString=function(){return this.type+":"+this.id};z.vb=function(){return this.toString()};z.qd=function(){return this.da.qd()+":"+this.toString()};
z.ki=function(){if(null!==this.type&&"Protein"===this.type&&!this.Ig){console.time("\t\t\tCompute HBonds");if(null===this.v){var e=this.ia,f=e.length;this.v=new ib;for(var g=1;g<f;g++){var h=e[g-1],k=e[g],l=this.v.findNode(k);null==l&&(l=this.v.Lg(k.toString(),k));var n=k.hc("CA"),r=k.hc("N"),q=k.hc("H");console.log("Predicting H position for residue ",k);if(h.sa()+h.lb().charCodeAt(0)===k.sa()+k.lb().charCodeAt(0)-1&&"PRO"!==h.aa){q=h.hc("C");h=h.hc("O");if(null==q||null==h)continue;q=q.sub(h);q=
q.normalize();h=r.add(q);q=new Ea;q.name="H";q.symbol="H";q.pos.x=h.x;q.pos.y=h.y;q.pos.z=h.z}if(null==q)console.log("TRACE : H position prediction failed for residue ",k);else for(k=0;k<f;k++)if(k!=g&&k!=g-1){var t=e[k],h=this.v.findNode(t);null==h&&(h=this.v.Lg(t.toString(),t));var x=t.hc("CA"),w=t.hc("C"),C=t.hc("O");if(null!=x&&null!=w&&null!=C&&!(9<x.distanceTo(n))){var x=q.distanceTo(C),t=q.distanceTo(w),C=r.distanceTo(C),F=r.distanceTo(w),w=-9.9;.5>x||.5>t||.5>C||.5>F||(w=27.888/C,w+=27.888/
t,w-=27.888/x,w-=27.888/F,-9.9>w&&(w=-9.9));if(-.5>w){console.log("acceptable H-bond found");var x=l.ck(h),G;null!=x?G=x.getAttribute("eH"):G=0;w<G&&(this.v.Kg(l,h,!0).setAttribute("eH",w),null!=x&&(console.log("- Replaces: ",x.toString()," ",G," kcal/mol"),this.v.Xk(x)))}}}}console.log(hBonds.Qc().length+" H-bonds found")}console.timeEnd("\t\t\tCompute HBonds");console.time("\t\t\tSSE Assignment");e=this.ia.length;for(f=0;f<e;f++)this.ia[f].ob=null;f=1;for(l=4;f+l<e;f++)if(Ob(this,this.ia[f-1],this.ia[f-
1+l])&&Ob(this,this.ia[f],this.ia[f+l]))for(g=f;g<f+l;g++)this.ia[g].ob=E.u;for(f=1;f+1<e;f++)for(g=f+3;g+1<e;g++)if(l=this.ia[f],n=this.ia[g],null===l.ob&&null===n.ob)if(Ob(this,this.ia[f-1],n)&&Ob(this,n,this.ia[f+1])||Ob(this,this.ia[g-1],l)&&Ob(this,l,this.ia[g+1]))l.ob=E.aa,n.ob=E.aa;else if(Ob(this,l,n)&&Ob(this,n,l)||Ob(this,this.ia[f-1],this.ia[g+1])&&Ob(this,this.ia[g-1],this.ia[f+1]))l.ob=E.v,n.ob=E.v;f=1;for(l=3;f+l<e;f++)if(Ob(this,this.ia[f-1],this.ia[f-1+l])&&Ob(this,this.ia[f],this.ia[f+
l])){n=!0;for(g=f;g<f+l;g++)if(null!=this.ia[g]){n=!1;break}for(g=f;g<f+l;g++)this.ia[g].ob=n?E.u:E.da}f=1;for(l=5;f+l<e;f++)if(Ob(this,this.ia[f-1],this.ia[f-1+l])&&Ob(this,this.ia[f],this.ia[f+l])){n=!0;for(g=f;g<f+l;g++)if(null!=this.ia[g]){n=!1;break}for(g=f;g<f+l;g++)this.ia[g].ob=n?E.u:E.da}for(n=3;5>=n;n++)for(f=0;f+n<e;f++)if(Ob(this,this.ia[f],this.ia[f+n]))for(g=f+1;g<f+n;g++)l=this.ia[g].ob,null==l&&(this.ia[g].ob=E.da);for(f=0;f<e;f++)l=this.ia[f].ob,null==l&&(this.ia[f].ob=E.fa);console.timeEnd("\t\t\tSSE Assignment");
this.Ig=!0}};function Ob(e,f,g){f=e.v.findNode(f);return null==f?!1:f.kk(e.v.findNode(g))}z.Rd=function(e){void 0===e&&(e=!0);for(var f="",g=this.ia,h=0,k="\x00",l=this.td()?"X":this.ye()?"N":"-",n=g.length,r=0;r<n;r++){var q=g[r];if(e&&0!=r)for(h=q.sa()-h+q.lb().charCodeAt(0)-k.charCodeAt(0);1<h--;)f+=l;f+=q.Di();h=q.sa();k=q.lb()}return f};z.ye=function(){return"DNA"==this.type||"RNA"==this.type};z.td=function(){return"Protein"==this.type||"Peptide"==this.type||"Small Peptide"==this.type};
z.Qi=function(){return this.ye()||this.td()};z.Pi=function(){return"Ligand"===this.type};z.tj=function(e){var f=new fc,g=[];g.push(new gc(this.toString(),this.Rd(!1)));g.push(new gc("ExternalSequence",e));f=f.da(g);e=f.Rd("ExternalSequence");f=f.Rd(this.toString());console.log(e,f);this.fa=f;console.log(f.fa())};
function qc(e){var f=[],g=0,h=e.ia,k=0,l;for(l in h){var n=h[l];if(null===n.type)k++;else{var r=f[n.type];void 0===r&&(r=0,f[n.type]=r,g++);f[n.type]++}}if(0!==g){var g=Infinity,q;for(r in f)h=f[r],0!==h&&h<g?(g=h,q=r):h===g&&r<q&&(q=r);g>=k&&("Protein"==q?(f=e.size(),e.type=20>f?"Small Peptide":60>f?"Peptide":"Protein"):e.type=q)}}function rc(){this._id=this.da=this.cc=this.ea=this.ob=this.type=this.aa=null;this.Wb="\x00";this.u=[];this.ta=new fa;this.za=this.fa=this.v=null}
function sc(e,f){e.da=f.Ib;e._id=f.rb;e.Wb=f.Kb}z=rc.prototype;z.ec=function(){return this.ea.ec()};function Gb(e,f){e.ea=f;null!==f&&void 0!==f&&e.Zd(f.sa())}z.sa=function(){return this._id};z.bd=function(e){if(this._id!=e){console.log("Changing residue id from "+this._id+" to "+e);this._id=e;for(var f=0;f<this.u.length;f++)Ma(this.u[f],e)}};z.lb=function(){return this.Wb};z.Vc=function(){return this.cc};z.Je=function(e){if(this.cc!=e){this.cc=e;for(var f=this.u.length,g=0;g<f;g++)g.Je(e)}};
z.ue=function(){return this.da};z.Zd=function(e){if(this.da!=e){this.da=e;null!==this.ea&&this.ea.bd(e);for(var f=this.u.length,g=0;g<f;g++)g.Zd(e)}};z.add=function(e){null===e&&console.warn("atom = null in Residue");null!==e.mb()&&e.mb()!==this&&console.warn(e," already belongs to ",e.mb());if(null===e.mb()){this.u.push(e);var f=new xc(e.name,e.ld);this.ta.Dc(f)||this.ta.set(f,e);e.wa=this;null!==this&&(Ma(e,e.wa.sa()),$a(e,e.wa.lb()),e.Je(e.wa.Vc()),e.Zd(e.wa.ue()))}};
z.remove=function(e){null===e&&console.warn("atom = null in Residue");if(e.mb()===this){this.u.remove(e);var f=new this.xb(e.name,e.ld);this.ta.remove(f,e)}};z.xa=function(){return this.u};z.Zj=function(e){for(var f=0;f<this.u.length;f++){var g=this.u[f];if(g.sa()==e)return g}return null};z.hc=function(e){var f=void 0;void 0===f&&(f="\x00");e=this.ta.get(new xc(e,f));if(null!==e)return e};
z.Ka=function(){if(null==this.v){this.v=new THREE.Vector3;for(var e=this.u.length,f=0;f<e;f++){var g=this.u[f].pos;this.v.x+=g.x;this.v.y+=g.y;this.v.z+=g.z}this.v.x/=e;this.v.y/=e;this.v.z/=e}return this.v};
z.dh=function(){if(null==this.fa)for(var e=this.u.length,f=0;f<e;f++){var g=this.u[f];if("CA"===g.name){this.fa=g.pos.clone();break}}if(null==this.fa){for(var h=this.Ka(),k=this.u[0],l=h.distanceTo(k.pos),e=this.u.length,f=0;f<e;f++){var g=this.u[f],n=h.distanceTo(g.pos);n<l&&(k=g,l=n)}this.fa=k.clone()}return this.fa};
z.mc=function(){if(null===this.za){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.u.length,h=0;h<g;h++){var k=this.u[h];e.x=Math.min(e.x,k.pos.x);e.y=Math.min(e.y,k.pos.y);e.z=Math.min(e.z,k.pos.z);f.x=Math.max(f.x,k.pos.x);f.y=Math.max(f.y,k.pos.y);f.z=Math.max(f.z,k.pos.z)}this.za=new Va(e,f)}return this.za};z.ye=function(){return"DNA"==this.type||"RNA"==this.type};
z.td=function(){return"Protein"==this.type||"Peptide"==this.type||"Small Peptide"==this.type};
z.Di=function(){switch(null!==this.aa?this.aa:this.cc){case "GLY":return"G";case "ALA":return"A";case "VAL":return"V";case "LEU":return"L";case "ILE":return"I";case "PRO":return"P";case "PHE":return"F";case "MET":return"M";case "TRP":return"W";case "SER":return"S";case "THR":return"T";case "ASN":return"N";case "GLN":return"Q";case "ASP":return"D";case "GLU":return"E";case "CYS":return"C";case "TYR":return"Y";case "HIS":return"H";case "LYS":return"K";case "ARG":return"R";case "ASX":return"B";case "GLX":return"Z";
case "A":case "DA":case "+A":return"A";case "C":case "DC":case "+C":return"C";case "G":case "DG":case "+G":return"G";case "T":case "DT":case "+T":return"T";case "U":case "DU":case "+U":return"U";case "I":case "DI":case "+I":return"I"}return null!=this.ea.type&&"Protein"===this.ea.type?"X":null==this.ea.type||"RNA"!==this.ea.type&&"DNA"!==this.ea.type?"?":"N"};z.toString=function(){return this.cc+":"+this._id};z.vb=function(){return this.cc+":"+this._id+":"+this.da};
z.qd=function(){return this.ea.qd()+":"+this.toString()};function xc(e,f){this.name=e;this.ld=f}xc.prototype.toString=function(){return this.name+":"+this.ld};xc.prototype.vb=function(){return this.name+":"+this.ld};
function Ec(e,f){null===e.aa&&console.warn("Error : stdResName must be set before guessing residue type");if(-1!==Fc.indexOf(e.aa))e.type="DNA";else if(-1!==Gc.indexOf(e.aa))e.type="RNA";else if(-1!==Hc.indexOf(e.aa))e.type="Protein";else if(-1!==Ic.indexOf(e.Vc()))e.type="Solvent";else if(-1!==Oc.indexOf(e.Vc()))e.type=null;else{var g=f.get(e.sa());null!=g&&g.name.endsWith(" ION")&&(e.type="Ion");e.type="Ligand"}}
var Hc="GLY ALA VAL LEU ILE PRO PHE MET TRP SER THR ASN GLN ASP GLU CYS TYR HIS LYS ARG".split(" "),Gc=["A","C","G","U","I"],Fc="DA DC DG DT DI DU +A +C +G +T +I +U T".split(" "),Oc="UNK ASX GLX N DN UNL UNX".split(" "),Ic=["HOH","DOD","GOL","EDO"];
function Pc(e,f,g){null===e&&console.warn("chainId null in Residue.Id");this.Ib=e;this.rb=f;this.Kb=g;this.toString=function(){return"\x00"!==this.Kb.charCodeAt(0)?this.Ib+":"+this.rb+":"+this.Kb:this.Ib+":"+this.rb};this.vb=function(){return"\x00"!==this.Kb.charCodeAt(0)?this.Ib+":"+this.rb+":"+this.Kb:this.Ib+":"+this.rb}}function E(e,f){this.name=e;this.code=f}E.fa=new E("Coil"," ");E.da=new E("Turn","T");E.u=new E("Helix","H");E.aa=new E("Strand","x");E.v=new E("Strand","X");
E.prototype.toString=function(){return name};function Tc(){this.Ik=!0;this.ci=this._id=this.Gg=null;this.aa=[];this.Xh=[];this.$e=new fa;this.We=new fa;this.Id=new fa;this.uj=[];this.v=[];this.da=new fa;this.u=null}z=Tc.prototype;z.Ka=function(){if(null===this.u){this.u=new THREE.Vector3;for(var e=this.v[0].aa,f=0;f<e.length;f++){var g=e[f].Ka();this.u.x+=g.x;this.u.y+=g.y;this.u.z+=g.z}this.u.x/=e.length;this.u.y/=e.length;this.u.z/=e.length}return this.u};z.ec=function(){return this.v[0].ec()};
z.sa=function(){return this._id};z.bd=function(e){null==this._id&&(this.Gg=e);this._id=e};z.Kh=function(){};z.setDate=function(){};z.dj=function(e){this.ci=e};z.gl=function(){};z.fi=function(e,f){f=null==e?this.aa:this.aa[e];null===this.aa&&(console.warn("ref inexistante dans lPdbFormat, cr\u00e9ation"),this.aa[e]=f)};z.el=function(e){this.Xh=e};
z.add=function(e){null===e&&console.warn("Error on adding model to structure : model = NULL");null!=e.Ec()&&e.Ec()!=this&&console.warn("Error on adding model to structure");null==e.Ec()&&(this.v.push(e),e.Ke(this))};z.remove=function(e){null===e&&console.warn("Error on removing structure");e.Ec()==this&&(this.v.remove(e),e.Ke(null))};z.Qf=function(){return this.v[0]};z.toString=function(){return this._id};z.vb=function(){return this.toString()};z.qd=function(){return this.toString()};
z.Oj=function(e){this.$e.__proto__=fa.prototype;this.$e.Ve={}.hasOwnProperty;this.Id.__proto__=fa.prototype;this.Id.Ve={}.hasOwnProperty;this.We.__proto__=fa.prototype;this.We.Ve={}.hasOwnProperty;this.da.__proto__=fa.prototype;this.da.Ve={}.hasOwnProperty;for(var f=e.length,g=0;g<f;g++){var h=new ab;this.add(h);for(var k=e[g],l=k.length,n=0;n<l;n++){var r=new Ea;r.type=k[n][0];r.id=k[n][1];r.name=k[n][2];r.ld=k[n][3];r.Je(k[n][4]);r.Zd(k[n][5]);Ma(r,k[n][6]);$a(r,k[n][7]);r.pos.x=k[n][8];r.pos.y=
k[n][9];r.pos.z=k[n][10];r.fa=k[n][11];r.ta=k[n][12];r.symbol=k[n][13];r.da=k[n][14];h.add(r)}}console.time("Time for building the models");Uc(this)};
function Uc(e){var f=e.$e,g=e.We,h=e.Id,k=e.v,l=!1,n,r=k.length;for(n=0;n<r;n++){for(var q=k[n],t=[],x=q.xa(),w=x.length,C=0;C<w;C++){var F=x[C],G=void 0,I=void 0,D;for(D in t)if(I=t[D],I.sa()===F.v&&I.ue()===F.ue()&&I.lb().charCodeAt(0)===F.lb().charCodeAt(0)){G=I;break}if(void 0===G){I=new Pc(F.ue(),F.v,F.lb());G=new rc;sc(G,I);G.Je(F.Vc());var K=f.get(I);G.aa=K?K.Oh:G.Vc();Ec(G,g);K=h.get(I);null!=K?(l||(l=!0),G.ob=K):G.ob=E.fa;t[I]=G}G.add(F)}var I=void 0,H;for(H in t){G=x=t[H];for(w=[];void 0!==
G&&null!==G&&-1===w.indexOf(H)&&!G.td()&&!G.ye();)if(w.push(H),C=e.da.get(H),null!=C){var I=C.Ea.Ib===H.Ib&&C.Ea.rb===H.rb&&C.Ea.Kb===H.Kb?C.pc:C.Ea,L;for(D in t)G=t[D],I.Ib===G.Ib&&I.rb===G.rb&&I.Kb===G.Kb&&(L=G);G=t[L]}void 0!==G&&G.type!==x.type&&(x.type=G.type)}x=[];for(G in t){var w=t[G],C=w.ue(),F=w.type+" "+C,O=x[F];void 0===O&&(O=new vb(C),q.add(O),x[F]=O);O.add(w);O.Ig=l}for(O in x)q=x[O],q.ia.sort(function(e,f){return e.Dg<f.Dg?-1:e.Dg>f.Dg?1:e._id<f._id?-1:e._id>f._id?1:e.Wb<f.Wb?-1:e.Wb>
f.Wb?1:0}),qc(q)}};

function zk(){this.si=this.Yg=this.ri=this.Xg=this.Wg=this.Vg=this.Kf=this.mh=this.Jh=this.lh=this.Ih=this.df=null}function Ak(e){this.pa=this.file=null;this.Xc=[];this.source=this.Qg=this.qh=this.title=null;this.ready=!1;this.Td=[];this.Td[Bk.id]=Bk;this.xe=[];this.resolution=null;null==e&&(e=!1);this.Cg=e;this.Wh=null}
Ak.prototype.parse=function(e,f){this.Wh=f;this.pa=new Tc;a:{var g=e.split("\n"),h,k=null,l;for(l in g){var n=g[l];if(n===this.Jl||n===this.Gl)break a;if(n===this.Hl){this.Xc.push([]);break a}var r=n.substring(0,6).trim(),q=null,t="";switch(r){case "ATOM":case "HETATM":var q=n.substring(76,78).trim(),x=n.substring(12,16).trim(),w=this.Xc[this.Xc.length-1];void 0===w&&(w=[],this.Xc.push(w));if(this.Cg&&"CA"!==x)break;if(!(null!==q&"H"===q)||this.Ri){var C=[],t=n.charAt(21);C.push(r);C.push(n.substring(6,
11).trim());C.push(x);C.push(" "!=n.charAt(16)?n.charAt(16):"\x00");C.push(n.substring(17,20).trim());C.push(t);C.push(parseFloat(n.substring(22,26).trim()));C.push(" "!=n.charAt(26)?n.charAt(26):"\x00");C.push(parseFloat(n.substring(30,38).trim()));C.push(parseFloat(n.substring(38,46).trim()));C.push(parseFloat(n.substring(46,54).trim()));C.push(n.substring(54,60).trim());C.push(n.substring(60,66).trim());C.push(q);79<=n.length&&C.push(toString(n.charAt(79))+toString(n.charAt(78)));w.push(C)}break;
case "HEADER":59<n.length?(this.pa.Kh(n.substring(10,50).trim()),this.pa.bd(n.substring(62,66).trim())):(this.pa.Kh(n.substring(10).trim()),this.pa.bd(file.getName().replaceAll("\\..*$","").toUpperCase()));this.pa.setDate(n.substring(50,59));break;case "TITLE":this.title=null===this.title?n.substring(10):this.title+(" "+n.substring(10));this.pa.dj(this.title);break;case "SOURCE":this.source+=n.substring(10);break;case "KEYWDS":this.qh+=n.substring(10);break;case "AUTHOR":this.Qg+=n.substring(10);
break;case "REMARK":n.substring(7,10).trim();if(~n.indexOf("RESOLUTION."))try{n.substring(n.indexOf("RESOLUTION.")+12).trim()}catch(F){console.warn("Error : ",F)}break;case "DBREF":k=new zk;k.df=n.charAt(12);k.Ih=n.substring(14,18).trim();k.lh=" "!==n.charAt(18)?n.charAt(18):"\x00";k.Jh=n.substring(20,24).trim();k.mh=" "!=n.charAt(24)?n.charAt(24):"\x00";k.Kf=n.substring(26,32).trim();k.Vg=n.substring(33,41).trim();k.Wg=n.substring(42,54).trim();k.Xg=n.substring(55,60).trim();k.ri=" "!=n.charAt(60)?
n.charAt(60):"\x00";k.Yg=n.substring(62,67<=n.length?67:n.length).trim();k.si=68<=n.length?n.charAt(67):"\x00";this.pa.fi(k.df,k);break;case "DBREF1":k=new zk;k.df=n.charAt(12);k.Ih=n.substring(14,18).trim();k.lh=" "!=n.charAt(18)?n.charAt(18):"\x00";k.Jh=n.substring(20,24).trim();k.mh=" "!=n.charAt(24)?n.charAt(24):"\x00";k.Kf=n.substring(26,32).trim();k.Wg=n.substring(47,67<=n.length?67:n.length).trim();this.pa.fi(k.df,k);break;case "DBREF2":k.Vg=n.substring(18,40).trim();k.Xg=n.substring(45,55).trim();
k.Yg=n.substring(57,67<=n.length?67:n.length).trim();break;case "MODRES":q=new Ck;q.name=n.substring(12,15).trim();t=n.charAt(16);r=n.substring(18,22).trim();x=" "!=n.charAt(22)?n.charAt(22):"\x00";q.Oh=n.substring(24,27).trim();q.description=30<=n.length?n.substring(29).trim():null;this.pa.$e.set(new Dk(t,r,x),q);break;case "HET":t=n.substring(7,10).trim();for(h in this.Td)if(h[0]===t){q=h[1];break}null===q&&(q=new Ek,q.id=t,q.description=31<=n.length?n.substring(30):null,this.Td[t]=q);t=n.charAt(12);
r=n.substring(13,17).trim();x=" "!=n.charAt(17)?n.charAt(17):"\x00";this.pa.We.set(new Dk(t,r,x),q);break;case "HETNAM":t=n.substring(11,14).trim();q=this.Td[t];q.name=null===q.name?n.substring(15):q.name+n.substring(15);break;case "HETSYN":t=n.substring(11,14).trim();this.xe[t]=void 0===this.xe[t]?n.substring(15):this.xe[t]+n.substring(15);break;case "FORMUL":t=n.substring(12,15).trim();q=this.Td[t];q.Nf=null===q.Nf?n.substring(19):q.Nf+n.substring(19);break;case "HELIX":t=n.charAt(19);q=parseInt(n.substring(21,
25));r=n.charAt(25);" "===r&&(r="\x00");h=parseInt(n.substring(33,37));q=parseInt(q);x=parseInt(h);for(h=q;h<=x;h++)this.pa.Id.set(new Dk(t,h,r),E.u);break;case "SHEET":for(t=n.charAt(21),q=parseInt(n.substring(22,26)),r=n.charAt(26)," "===r&&(r="\x00"),h=parseInt(n.substring(33,37)),n=-1===parseInt(n.substring(38,40))?E.v:E.aa,q=parseInt(q),x=parseInt(h),h=q;h<=x;h++)this.pa.Id.set(new Dk(t,h,r),n)}}this.finish();this.ready=!0}};
Ak.prototype.finish=function(){this.pa.el(this.pa.Xh.concat(null));this.Qg=this.qh=this.source=null;for(var e in this.xe){var f=this.Td[e];f.ij=f.ij.concat(this.xe[e].split("\\s*;\\s*"))}this.xe=this.Td=null;this.Wh.apply(this,[this.pa,this.Xc])};function Ck(){this.description=this.Oh=this.name=null}function Fk(e){this.pa=null;this.Xc=[];this.ih=!1;this.cf=null;this.Fa=[];this.Ri=!1;this.Tk=!0;this.kj=[];this.ng=[];this.ej=new fa;null==e&&(e=!1);this.Cg=e}
Fk.prototype.parse=function(e,f){this.pa=new Tc;this.ng[Bk.id]=Bk;Gk.parse(e,this);f.apply(this,[this.pa,this.Xc])};function Hk(e,f,g){if(!e.ih){var h=f.split(".",2);null!==e.cf&&e.cf!==h[0]&&Ik(e);e.cf=h[0]}e.Fa[f]=g}function Ik(e){null!==e.cf&&(Jk(e),e.Fa=[],e.cf=null)}function Kk(e,f){var g=parseInt(e.Fa[f]);isNaN(g)&&(g=0);return g}Fk.prototype.getFloatValue=function(e){e=parseFloat(this.Fa[e]);isNaN(e)&&(e=0);return e};
Fk.prototype.getStringValue=function(e,f){var g=this.Fa[e];null==g&&null!=f&&(g=this.Fa[f]);if("."===g||"?"===g)return"\x00";void 0!==g&&(g=g.replace('"',""));return g};
function Jk(e){if(void 0!==e.Fa["_atom_site.id"]){var f=parseInt(e.Fa["_atom_site.pdbx_PDB_model_num"]);if(!(e.Tk&&1<f)){var g=e.Xc[f-1];void 0===g&&(g=[],e.Xc[f-1]=g);if(!e.Cg||"CA"===e.getStringValue("_atom_site.label_atom_id")){var f=[],h=e.getStringValue("_atom_site.type_symbol");null!==h&"H"===h&&!e.Ri||(f.push(e.getStringValue("_atom_site.group_PDB")),f.push(Kk(e,"_atom_site.id")),f.push(e.getStringValue("_atom_site.auth_atom_id","_atom_site.label_atom_id").replace(/"/g,"")),f.push(e.getStringValue("_atom_site.label_alt_id").replace(/"/g,
"")),f.push(e.getStringValue("_atom_site.auth_comp_id","_atom_site.label_comp_id")),f.push(e.getStringValue("_atom_site.auth_asym_id","_atom_site.label_asym_id")),f.push(Kk(e,"_atom_site.auth_seq_id")),f.push(e.getStringValue("_atom_site.pdbx_PDB_ins_code")),f.push(e.getFloatValue("_atom_site.Cartn_x")),f.push(e.getFloatValue("_atom_site.Cartn_y")),f.push(e.getFloatValue("_atom_site.Cartn_z")),f.push(e.getFloatValue("_atom_site.occupancy")),f.push(e.getFloatValue("_atom_site.B_iso_or_equiv")),f.push(e.getStringValue("_atom_site.type_symbol")),
f.push(Kk(e,"_atom_site.pdbx_formal_charge")),g.push(f))}}}else if(void 0!==e.Fa["_struct_keywords.entry_id"])e.pa.Kh(e.getStringValue("_struct_keywords.pdbx_keywords")),null!==e.getStringValue("_struct_keywords.text")&&e.getStringValue("_struct_keywords.text");else if(void 0!==e.Fa["_audit_author.name"])e.pa.uj.push(e.getStringValue("_audit_author.name"));else if(void 0!==e.Fa["_database_PDB_rev.num"])g=e.getStringValue("_database_PDB_rev.date_original"),null!==g&&e.pa.setDate(g);else if(void 0!==
e.Fa["_struct.entry_id"])e.pa.dj(e.getStringValue("_struct.title"));else if(void 0!==e.Fa["_refine.entry_id"])e.pa.gl(e.getFloatValue("_refine.ls_d_res_high",NaN));else if(void 0!==e.Fa["_entity.id"])"polymer"===e.Fa["_entity.type"]&&(g=Kk(e,"_entity.id"));else if(void 0===e.Fa["_entity_poly.entity_id"]&&void 0===e.Fa["_entity_name_com.entity_id"])if(void 0!==e.Fa["_struct_ref.id"])g=Kk(e,"_struct_ref.id"),f=new zk,e.kj[g]=f,f.Kf=e.getStringValue("_struct_ref.db_name"),f.Wg=e.getStringValue("_struct_ref.db_code"),
f.Vg=e.getStringValue("_struct_ref.pdbx_db_accession");else if(void 0!==e.Fa["_struct_ref_seq.align_id"])g=Kk(e,"_struct_ref_seq.ref_id"),f=e.kj[g],f.df=e.getStringValue("_struct_ref_seq.pdbx_strand_id"),f.Ih=Kk(e,"_struct_ref_seq.seq_align_beg"),f.lh=e.getStringValue("_struct_ref_seq.pdbx_seq_align_beg_ins_code"),f.Jh=Kk(e,"_struct_ref_seq.seq_align_end"),f.mh=e.getStringValue("_struct_ref_seq.pdbx_seq_align_end_ins_code"),f.Xg=Kk(e,"_struct_ref_seq.db_align_beg"),f.ri=e.getStringValue("_struct_ref_seq.pdbx_db_align_beg_ins_code"),
f.Yg=Kk(e,"_struct_ref_seq.db_align_end"),f.si=e.getStringValue("_struct_ref_seq.pdbx_db_align_end_ins_code");else if(void 0!==e.Fa["_pdbx_struct_mod_residue.id"]){f=new Ck;f.name=e.getStringValue("_pdbx_struct_mod_residue.auth_comp_id");f.Oh=e.getStringValue("_pdbx_struct_mod_residue.parent_comp_id");f.description=e.getStringValue("_pdbx_struct_mod_residue.details");var g=e.getStringValue("_pdbx_struct_mod_residue.auth_asym_id"),h=Kk(e,"_pdbx_struct_mod_residue.auth_seq_id"),k=e.getStringValue("_pdbx_struct_mod_residue.PDB_ins_code");
e.pa.$e.set(new Dk(g,h,k),f)}else if(void 0!==e.Fa["_pdbx_nonpoly_scheme.asym_id"])g=e.getStringValue("_pdbx_nonpoly_scheme.mon_id"),f=e.ng[g],void 0===f&&(f=new Ek,f.id=g,e.ng[g]=f),g=e.getStringValue("_pdbx_nonpoly_scheme.pdb_strand_id"),h=Kk(e,"_pdbx_nonpoly_scheme.pdb_seq_num"),k=e.getStringValue("_pdbx_nonpoly_scheme.pdb_ins_code"),e.pa.We.set(new Dk(g,h,k),f);else if(void 0!==e.Fa["_chem_comp.id"])g=e.getStringValue("_chem_comp.id"),f=e.ng[g],void 0!==f&&(f.name=e.getStringValue("_chem_comp.name"),
null!=e.getStringValue("_chem_comp.pdbx_synonyms")&&e.getStringValue("_chem_comp.pdbx_synonyms"),f.Nf=e.getStringValue("_chem_comp.formula"));else if(void 0===e.Fa["_struct_conn.id"])if(void 0!==e.Fa["_struct_conf.id"]){e.getStringValue("_struct_conf.conf_type_id");var g=e.getStringValue("_struct_conf.beg_auth_asym_id"),l=Kk(e,"_struct_conf.beg_auth_seq_id"),f=e.getStringValue("_struct_conf.pdbx_beg_PDB_ins_code");e.getStringValue("_struct_conf.end_auth_asym_id");k=Kk(e,"_struct_conf.end_auth_seq_id");
e.getStringValue("_struct_conf.pdbx_end_PDB_ins_code");for(var n=parseInt(l),k=parseInt(k);n<=k;n++)e.pa.Id.set(new Dk(g,n,f),E.u)}else if(void 0!==e.Fa["_struct_sheet_range.id"])for(h=E.aa,g=e.getStringValue("_struct_sheet_range.beg_auth_asym_id"),l=Kk(e,"_struct_sheet_range.beg_auth_seq_id"),f=e.getStringValue("_struct_sheet_range.pdbx_beg_PDB_ins_code"),e.getStringValue("_struct_sheet_range.end_auth_asym_id"),k=Kk(e,"_struct_sheet_range.end_auth_seq_id"),e.getStringValue("_struct_sheet_range.pdbx_end_PDB_ins_code"),
n=e.getStringValue("_struct_sheet_range.id"),n=e.ej.get(new Dk(g,n,"0")),"anti-parallel"===n&&(h=E.v),n=parseInt(l),k=parseInt(k);n<=k;n++)e.pa.Id.set(new Dk(g,n,f),h);else void 0!==e.Fa["_struct_sheet_order.sheet_id"]&&(g=e.getStringValue("_struct_sheet_order.sheet_id"),e.getStringValue("_struct_sheet_order.range_id_1"),f=e.getStringValue("_struct_sheet_order.range_id_2"),n=e.getStringValue("_struct_sheet_order.sense"),e.ej.set(new Dk(g,f,"\x00"),n))}
function Dk(e,f,g){null===e&&console.warn("chainId null in Residue.Id");this.Ib=e;this.rb=f;this.Kb=g;this.toString=function(){return"\x00"!==this.Kb.charCodeAt(0)?this.Ib+":"+this.rb+":"+this.Kb:this.Ib+":"+this.rb};this.vb=function(){return"\x00"!==this.Kb.charCodeAt(0)?this.Ib+":"+this.rb+":"+this.Kb:this.Ib+":"+this.rb}}
onmessage=function(e){function f(e,f){postMessage(JSON.stringify(e));postMessage(JSON.stringify(f))}var g=e.data[0],h=e.data[2],k;k=e.data[1]?new Fk:new Ak;if(h)k.parse(g,f);else{console.time("Time for downloading the file");var l=new XMLHttpRequest;l.open("GET",g,!0);l.onreadystatechange=function(){console.timeEnd("Time for downloading the file");var e=l.status;if(4==l.readyState)if(200==e)postMessage(new Blob([l.responseText],{type:"text/plain"})),k.parse(l.responseText,f);else{var h={type:"error",
msg:""};switch(e){case 404:h.msg="File not found, "+g;break;case 500:h.msg="Server error";break;case 0:h.msg="Request aborted";break;default:h.msg="Unknown error "+e}postMessage(JSON.stringify(h))}};l.send(null)}};function Ek(){this.name=this.id=null;this.ij=[];this.description=this.Nf=null}var Bk=new Ek;Bk.id="HOH";Bk.name="WATER";E=function(e,f){this.name=e;this.code=f};E.fa=new E("Coil"," ");E.da=new E("Turn","T");E.u=new E("Helix","H");E.aa=new E("Strand","x");E.v=new E("Strand","X");
E.prototype.toString=function(){return name};
var Gk=function(){function e(f,g,h,k){this.message=f;this.location=k;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,e)}(function(e,g){function h(){this.constructor=e}h.prototype=g.prototype;e.prototype=new h})(e,Error);return{SyntaxError:e,parse:function(f,g){function h(e){var g=tb[e],h,k;if(g)return g;for(h=e-1;!tb[h];)h--;g=tb[h];for(g={line:g.line,jb:g.jb,$b:g.$b};h<e;)k=f.charAt(h),"\n"===k?(g.$b||g.line++,g.jb=1,g.$b=!1):"\r"===k||"\u2028"===
k||"\u2029"===k?(g.line++,g.jb=1,g.$b=!0):(g.jb++,g.$b=!1),h++;return tb[e]=g}function k(e,f){var g=h(e),k=h(f);return{start:{offset:e,line:g.line,jb:g.jb},end:{offset:f,line:k.line,jb:k.jb}}}function l(e){A<ga||(A>ga&&(ga=A,Zb=[]),Zb.push(e))}function n(){var e,g,h,k,l,m,n;e=S();if(e===y&&(e=O(),e===y))if(e=A,g=r(),g!==y){h=A;k=[];l=A;m=O();m!==y?(n=r(),n!==y?l=m=[m,n]:(A=l,l=y)):(A=l,l=y);for(;l!==y;)k.push(l),l=A,m=O(),m!==y?(n=r(),n!==y?l=m=[m,n]:(A=l,l=y)):(A=l,l=y);h=k!==y?f.substring(h,A):
k;if(h!==y){k=[];for(l=O();l!==y;)k.push(l),l=O();k!==y?e=g=[g,h,k]:(A=e,e=y)}else A=e,e=y}else A=e,e=y;return e}function r(){var e,g,h,k,m,n;k=h=g=e=A;var r,w,x,C,D;n=m=A;Kc.test(f.charAt(A))?(r=f.charAt(A),A++):(r=y,0===J&&l(ic));r===y&&(Bb.test(f.charAt(A))?(r=f.charAt(A),A++):(r=y,0===J&&l(jc)));r!==y?(Ja.test(f.charAt(A))?(w=f.charAt(A),A++):(w=y,0===J&&l(Wa)),w===y&&(fb.test(f.charAt(A))?(w=f.charAt(A),A++):(w=y,0===J&&l(ia))),w!==y?(Z.test(f.charAt(A))?(x=f.charAt(A),A++):(x=y,0===J&&l(ca)),
x===y&&(Ca.test(f.charAt(A))?(x=f.charAt(A),A++):(x=y,0===J&&l(Cb))),x!==y?(Ja.test(f.charAt(A))?(C=f.charAt(A),A++):(C=y,0===J&&l(Wa)),C===y&&(fb.test(f.charAt(A))?(C=f.charAt(A),A++):(C=y,0===J&&l(ia))),C!==y?(ob.test(f.charAt(A))?(D=f.charAt(A),A++):(D=y,0===J&&l(ra)),D!==y?n=r=[r,w,x,C,D]:(A=n,n=y)):(A=n,n=y)):(A=n,n=y)):(A=n,n=y)):(A=n,n=y);m=n!==y?f.substring(m,A):n;k=m!==y?f.substring(k,A):m;if(k!==y){m=A;k=[];n=F();if(n!==y)for(;n!==y;)k.push(n),n=F();else k=y;m=k!==y?f.substring(m,A):k;m!==
y?(V.de.pa.bd(m),h=void 0):(A=h,h=y)}else A=h,h=y;g=h!==y?f.substring(g,A):h;if(g!==y){h=[];k=A;m=O();m!==y?(n=t(),n===y&&(n=q()),n!==y?k=m=[m,n]:(A=k,k=y)):(A=k,k=y);for(;k!==y;)h.push(k),k=A,m=O(),m!==y?(n=t(),n===y&&(n=q()),n!==y?k=m=[m,n]:(A=k,k=y)):(A=k,k=y);h!==y?e=g=[g,h]:(A=e,e=y)}else A=e,e=y;return e}function q(){var e,g,h,k,l,m;g=e=A;h=Tb();h!==y?(k=A,l=F(),k=l!==y?f.substring(k,A):l,k!==y?g=h=[h,k]:(A=g,g=y)):(A=g,g=y);if(g!==y){h=[];k=A;l=O();l!==y?(m=t(),m!==y?k=l=[l,m]:(A=k,k=y)):(A=
k,k=y);if(k!==y)for(;k!==y;)h.push(k),k=A,l=O(),l!==y?(m=t(),m!==y?k=l=[l,m]:(A=k,k=y)):(A=k,k=y);else h=y;h!==y?(k=O(),k!==y?(l=Tb(),l!==y?e=g=[g,h,k,l]:(A=e,e=y)):(A=e,e=y)):(A=e,e=y)}else A=e,e=y;return e}function t(){var e,g,h,k;e=A;g=Hb();g!==y&&(g=V.de,Ik(g),g.ih=!0,V.uh=[],V.i=0,g=void 0);if(g!==y){h=[];g=x();if(g!==y)for(;g!==y;)h.push(g),g=x();else h=y;if(h!==y){g=[];for(h=w();h!==y;)g.push(h),h=w();g!==y?(e=V.de,e.ih=!1,e.Fa=[],e=void 0):(A=e,e=y)}else A=e,e=y}else A=e,e=y;e===y&&(g=e=A,
h=pa(),g=h!==y?f.substring(g,A):h,g!==y?(h=O(),h!==y?(h=A,k=na(),h=k!==y?f.substring(h,A):k,h!==y?(Hk(V.de,g,h),e=void 0):(A=e,e=y)):(A=e,e=y)):(A=e,e=y));return e}function x(){var e,f;e=A;f=O();f!==y?(f=pa(),f!==y?(V.uh.push(f),e=void 0):(A=e,e=y)):(A=e,e=y);return e}function w(){var e,f,g;e=A;f=O();f!==y?(g=A,J++,f=Hb(),J--,f===y?g=void 0:(A=g,g=y),g!==y?(f=na(),f!==y?(e=V.uh.length,Hk(V.de,V.uh[V.i%e],f),V.i++,0===V.i%e&&Jk(V.de),e=void 0):(A=e,e=y)):(A=e,e=y)):(A=e,e=y);return e}function C(){var e;
yb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&l(tc));return e}function F(){var e;e=C();e===y&&(e=I(),e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&l(ta)),e===y&&(e=D(),e===y&&(zb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&l(hd)),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&l(cb)),e===y&&(93===f.charCodeAt(A)?(e=nb,A++):(e=y,0===J&&l(db))))))));return e}function G(){var e;e=C();e===y&&(e=I(),e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&l(ta)),e===
y&&(e=D(),e===y&&(ob.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&l(ra)),e===y&&(e=ba(),e===y&&(e=Y(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&l(cb)),e===y&&(93===f.charCodeAt(A)?(e=nb,A++):(e=y,0===J&&l(db))))))))));return e}function I(){var e;34===f.charCodeAt(A)?(e=eb,A++):(e=y,0===J&&l(Na));return e}function D(){var e;39===f.charCodeAt(A)?(e=pb,A++):(e=y,0===J&&l(Ab));return e}function K(){var e;e=C();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&l(ta)),e===y&&(95===
f.charCodeAt(A)?(e=Oa,A++):(e=y,0===J&&l(qa)),e===y&&(e=ba(),e===y&&(e=Y(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&l(cb)),e===y&&(59===f.charCodeAt(A)?(e=N,A++):(e=y,0===J&&l(R)),e===y&&(93===f.charCodeAt(A)?(e=nb,A++):(e=y,0===J&&l(db)),e===y&&(e=D(),e===y&&(e=I())))))))));return e}function H(){var e;e=C();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&l(ta)),e===y&&(95===f.charCodeAt(A)?(e=Oa,A++):(e=y,0===J&&l(qa)),e===y&&(e=ba(),e===y&&(e=Y(),e===y&&(91===f.charCodeAt(A)?
(e=Ub,A++):(e=y,0===J&&l(cb)),e===y&&(59===f.charCodeAt(A)?(e=N,A++):(e=y,0===J&&l(R)),e===y&&(93===f.charCodeAt(A)?(e=nb,A++):(e=y,0===J&&l(db)),e===y&&(e=I()))))))));return e}function L(){var e;e=C();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&l(ta)),e===y&&(95===f.charCodeAt(A)?(e=Oa,A++):(e=y,0===J&&l(qa)),e===y&&(e=ba(),e===y&&(e=Y(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&l(cb)),e===y&&(59===f.charCodeAt(A)?(e=N,A++):(e=y,0===J&&l(R)),e===y&&(93===f.charCodeAt(A)?
(e=nb,A++):(e=y,0===J&&l(db)),e===y&&(e=D()))))))));return e}function O(){var e,g,h;e=A;g=[];h=X();h===y&&(h=ba(),h===y&&(h=Y(),h===y&&(h=wa())));if(h!==y)for(;h!==y;)g.push(h),h=X(),h===y&&(h=ba(),h===y&&(h=Y(),h===y&&(h=wa())));else g=y;return e=g!==y?f.substring(e,A):g}function S(){var e,g,h,k,m,n;e=A;g=[];h=A;35===f.charCodeAt(A)?(k=qb,A++):(k=y,0===J&&l(Ia));if(k!==y){m=[];for(n=K();n!==y;)m.push(n),n=K();m!==y?(n=wa(),n===y&&(n=Ib()),n!==y?h=k=[k,m,n]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;if(h!==
y)for(;h!==y;)if(g.push(h),h=A,35===f.charCodeAt(A)?(k=qb,A++):(k=y,0===J&&l(Ia)),k!==y){m=[];for(n=K();n!==y;)m.push(n),n=K();m!==y?(n=wa(),n===y&&(n=Ib()),n!==y?h=k=[k,m,n]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;else g=y;return e=g!==y?f.substring(e,A):g}function X(){var e,f,g;e=A;f=[];g=ba();g===y&&(g=Y(),g===y&&(g=wa()));if(g!==y)for(;g!==y;)f.push(g),g=ba(),g===y&&(g=Y(),g===y&&(g=wa()));else f=y;f!==y?(g=S(),g!==y?e=f=[f,g]:(A=e,e=y)):(A=e,e=y);return e}function pa(){var e,g,h,k,m;g=e=A;95===f.charCodeAt(A)?
(h=Oa,A++):(h=y,0===J&&l(qa));if(h!==y){k=[];m=F();if(m!==y)for(;m!==y;)k.push(m),m=F();else k=y;k!==y?g=h=[h,k]:(A=g,g=y)}else A=g,g=y;return e=g!==y?f.substring(e,A):g}function na(){var e,g;e=A;var h,k,m,n,q,r,t,w,x;g=A;59===f.charCodeAt(A)?(h=N,A++):(h=y,0===J&&l(R));if(h!==y){k=[];for(m=K();m!==y;)k.push(m),m=K();if(k!==y)if(m=wa(),m!==y){n=[];r=q=A;t=G();if(t!==y){w=[];for(x=K();x!==y;)w.push(x),x=K();w!==y?r=t=[t,w]:(A=r,r=y)}else A=r,r=y;r===y&&(r=null);r!==y?(t=wa(),t!==y?q=r=[r,t]:(A=q,q=
y)):(A=q,q=y);for(;q!==y;){n.push(q);r=q=A;t=G();if(t!==y){w=[];for(x=K();x!==y;)w.push(x),x=K();w!==y?r=t=[t,w]:(A=r,r=y)}else A=r,r=y;r===y&&(r=null);r!==y?(t=wa(),t!==y?q=r=[r,t]:(A=q,q=y)):(A=q,q=y)}n!==y?(59===f.charCodeAt(A)?(q=N,A++):(q=y,0===J&&l(R)),q!==y?g=h=[h,k,m,n,q]:(A=g,g=y)):(A=g,g=y)}else A=g,g=y;else A=g,g=y}else A=g,g=y;e=g!==y?f.substring(e,A):g;if(e===y){h=g=e=A;k=I();if(k!==y){m=[];for(n=L();n!==y;)m.push(n),n=L();m!==y?(n=I(),n!==y?h=k=[k,m,n]:(A=h,h=y)):(A=h,h=y)}else A=h,
h=y;g=h!==y?f.substring(g,A):h;if(g===y){g=A;h=D();if(h!==y){k=[];m=H();m===y&&(m=A,n=D(),n!==y?(q=A,J++,r=O(),J--,r===y?q=void 0:(A=q,q=y),q!==y?m=n=[n,q]:(A=m,m=y)):(A=m,m=y));for(;m!==y;)k.push(m),m=H(),m===y&&(m=A,n=D(),n!==y?(q=A,J++,r=O(),J--,r===y?q=void 0:(A=q,q=y),q!==y?m=n=[n,q]:(A=m,m=y)):(A=m,m=y));k!==y?(m=D(),m!==y?g=h=[h,k,m]:(A=g,g=y)):(A=g,g=y)}else A=g,g=y;if(g===y)if(g=A,h=C(),h!==y){k=A;m=[];for(n=F();n!==y;)m.push(n),n=F();k=m!==y?f.substring(k,A):m;k!==y?g=h=[h,k]:(A=g,g=y)}else A=
g,g=y}e=g!==y?f.substring(e,A):g;e===y&&(e=A,Vb.test(f.charAt(A))?(g=f.charAt(A),A++):(g=y,0===J&&l(Jc)),e=g!==y?f.substring(e,A):g,e===y&&(e=A,hc.test(f.charAt(A))?(g=f.charAt(A),A++):(g=y,0===J&&l(Wb)),e=g!==y?f.substring(e,A):g))}return e}function Hb(){var e,g,h,k,m,n,q;g=e=A;rb.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&l(sb));h===y&&(Ka.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&l(Db)));h!==y?(sa.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&l(Pa)),k===y&&(la.test(f.charAt(A))?
(k=f.charAt(A),A++):(k=y,0===J&&l(Xa))),k!==y?(sa.test(f.charAt(A))?(m=f.charAt(A),A++):(m=y,0===J&&l(Pa)),m===y&&(la.test(f.charAt(A))?(m=f.charAt(A),A++):(m=y,0===J&&l(Xa))),m!==y?(ua.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===J&&l(gb)),n===y&&(uc.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===J&&l(vc))),n!==y?(ob.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&l(ra)),q!==y?g=h=[h,k,m,n,q]:(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y);return e=g!==y?f.substring(e,A):g}function Tb(){var e,
g,h,k,m,n,q;g=e=A;Xb.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&l(xa));h===y&&(ma.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&l(ya)));h!==y?(Ja.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&l(Wa)),k===y&&(fb.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&l(ia))),k!==y?(Lc.test(f.charAt(A))?(m=f.charAt(A),A++):(m=y,0===J&&l(Da)),m===y&&(Kb.test(f.charAt(A))?(m=f.charAt(A),A++):(m=y,0===J&&l(Mc))),m!==y?(Nc.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===J&&l(Yb)),n===y&&(Qa.test(f.charAt(A))?
(n=f.charAt(A),A++):(n=y,0===J&&l(La))),n!==y?(ob.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&l(ra)),q!==y?g=h=[h,k,m,n,q]:(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y);return e=g!==y?f.substring(e,A):g}function ba(){var e;32===f.charCodeAt(A)?(e=kc,A++):(e=y,0===J&&l(wc));return e}function Y(){var e;9===f.charCodeAt(A)?(e=lc,A++):(e=y,0===J&&l(hb));return e}function wa(){var e;10===f.charCodeAt(A)?(e=Lb,A++):(e=y,0===J&&l(Ya));e===y&&(13===f.charCodeAt(A)?(e=Mb,A++):(e=y,0===J&&l(mc)),
e===y&&(f.substr(A,2)===Eb?(e=Eb,A+=2):(e=y,0===J&&l(va))));return e}function Ib(){var e,g;e=A;J++;f.length>A?(g=f.charAt(A),A++):(g=y,0===J&&l(Ra));J--;g===y?e=void 0:(A=e,e=y);return e}this.de=g;var V=this,m=1<arguments.length?arguments[1]:{},y={},Jb={start:n},oa=n,yb=/^[a-zA-Z0-9!%&*()+,-.\/:<=>?@\^`{|}~\\]/,tc={type:"class",value:"[a-zA-Z0-9!%&*()+,-\\./:<=>?@\\^`{|}~\\\\]",description:"[a-zA-Z0-9!%&*()+,-\\./:<=>?@\\^`{|}~\\\\]"},bb=/^[#$]/,ta={type:"class",value:"[#$]",description:"[#$]"},zb=
/^[_;']/,hd={type:"class",value:"[_;']",description:"[_;']"},Ub="[",cb={type:"literal",value:"[",description:'"["'},nb="]",db={type:"literal",value:"]",description:'"]"'},ob=/^[_]/,ra={type:"class",value:"[_]",description:"[_]"},eb='"',Na={type:"literal",value:'"',description:'"\\""'},pb="'",Ab={type:"literal",value:"'",description:'"\'"'},Oa="_",qa={type:"literal",value:"_",description:'"_"'},N=";",R={type:"literal",value:";",description:'";"'},qb="#",Ia={type:"literal",value:"#",description:'"#"'},
Vb=/^[.]/,Jc={type:"class",value:"[.]",description:"[.]"},hc=/^[?]/,Wb={type:"class",value:"[?]",description:"[?]"},Kc=/^[D]/,ic={type:"class",value:"[D]",description:"[D]"},Bb=/^[d]/,jc={type:"class",value:"[d]",description:"[d]"},Ja=/^[A]/,Wa={type:"class",value:"[A]",description:"[A]"},fb=/^[a]/,ia={type:"class",value:"[a]",description:"[a]"},Z=/^[T]/,ca={type:"class",value:"[T]",description:"[T]"},Ca=/^[t]/,Cb={type:"class",value:"[t]",description:"[t]"},rb=/^[L]/,sb={type:"class",value:"[L]",
description:"[L]"},Ka=/^[l]/,Db={type:"class",value:"[l]",description:"[l]"},sa=/^[O]/,Pa={type:"class",value:"[O]",description:"[O]"},la=/^[o]/,Xa={type:"class",value:"[o]",description:"[o]"},ua=/^[P]/,gb={type:"class",value:"[P]",description:"[P]"},uc=/^[p]/,vc={type:"class",value:"[p]",description:"[p]"},Xb=/^[S]/,xa={type:"class",value:"[S]",description:"[S]"},ma=/^[s]/,ya={type:"class",value:"[s]",description:"[s]"},Lc=/^[V]/,Da={type:"class",value:"[V]",description:"[V]"},Kb=/^[v]/,Mc={type:"class",
value:"[v]",description:"[v]"},Nc=/^[E]/,Yb={type:"class",value:"[E]",description:"[E]"},Qa=/^[e]/,La={type:"class",value:"[e]",description:"[e]"},kc=" ",wc={type:"literal",value:" ",description:'" "'},lc="\t",hb={type:"literal",value:"\t",description:'"\\t"'},Lb="\n",Ya={type:"literal",value:"\n",description:'"\\n"'},Mb="\r",mc={type:"literal",value:"\r",description:'"\\r"'},Eb="\r\n",va={type:"literal",value:"\r\n",description:'"\\r\\n"'},Ra={type:"any",description:"any character"},A=0,tb=[{line:1,
jb:1,$b:!1}],ga=0,Zb=[],J=0,za;if("startRule"in m){if(!(m.nf in Jb))throw Error("Can't start parsing from rule \""+m.nf+'".');oa=Jb[m.nf]}za=oa();if(za!==y&&A===f.length)return za;za!==y&&A<f.length&&l({type:"end",description:"end of input"});throw function(f,g,h,k){function l(e){var f=1;for(e.sort(function(e,f){return e.description<f.description?-1:e.description>f.description?1:0});f<e.length;)e[f-1]===e[f]?e.splice(f,1):f++}function m(e,f){function g(e){function f(e){return e.charCodeAt(0).toString(16).toUpperCase()}
return e.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\x08/g,"\\b").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\f/g,"\\f").replace(/\r/g,"\\r").replace(/[\x00-\x07\x0B\x0E\x0F]/g,function(e){return"\\x0"+f(e)}).replace(/[\x10-\x1F\x80-\xFF]/g,function(e){return"\\x"+f(e)}).replace(/[\u0100-\u0FFF]/g,function(e){return"\\u0"+f(e)}).replace(/[\u1000-\uFFFF]/g,function(e){return"\\u"+f(e)})}var h=Array(e.length),k;for(k=0;k<e.length;k++)h[k]=e[k].description;h=1<e.length?h.slice(0,-1).join(", ")+
" or "+h[e.length-1]:h[0];k=f?'"'+g(f)+'"':"end of input";return"Expected "+h+" but "+k+" found."}null!==g&&l(g);return new e(null!==f?f:m(g,h),0,0,k)}(null,Zb,ga<f.length?f.charAt(ga):null,ga<f.length?k(ga,ga+1):k(ga,ga));}}}();
}(biovizWorkerNamespace));